# Generated by Django 5.2.10 on 2026-02-04 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system_admin', 'system_admin'), ('company_manager', 'company_manager'), ('sales_engineer', 'sales_engineer'), ('production_engineer', 'production_engineer'), ('planner', 'planner'), ('purchasing', 'purchasing'), ('goods_receipt_clerk', 'goods_receipt_clerk'), ('section_supervisor', 'section_supervisor'), ('quality_inspector', 'quality_inspector'), ('operator', 'operator')], max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.company')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.facility')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.workstation')),
            ],
            options={
                'db_table': 'user_memberships',
            },
        ),
    ]
