# Generated by Django 5.2.10 on 2026-02-04 19:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('part_no', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('part_type', models.CharField(choices=[('finished_good', 'finished_good'), ('semi_finished', 'semi_finished'), ('raw_material', 'raw_material'), ('consumable', 'consumable'), ('fixed_asset', 'fixed_asset')], max_length=32)),
                ('procurement_strategy', models.CharField(choices=[('make', 'make'), ('buy', 'buy')], max_length=8)),
                ('is_saleable', models.BooleanField(default=False)),
                ('standard_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=4, help_text='Read-only (updated by GR/QC pass flow).', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_parts',
                'indexes': [models.Index(fields=['company_id', 'part_no'], name='inventory_p_company_dcec47_idx'), models.Index(fields=['company_id', 'part_type'], name='inventory_p_company_0d2dd8_idx')],
                'constraints': [models.UniqueConstraint(fields=('company_id', 'part_no'), name='uq_inventory_part_company_partno')],
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('revision_index', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='inventory.part')),
            ],
            options={
                'db_table': 'inventory_boms',
            },
        ),
        migrations.CreateModel(
            name='PartStockSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('available_qty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('weighted_avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('last_purchase_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_production_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_summary', to='inventory.part')),
            ],
            options={
                'db_table': 'inventory_part_stock_summary',
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('movement_type', models.CharField(choices=[('in', 'in'), ('out', 'out'), ('adjustment', 'adjustment')], max_length=16)),
                ('source_type', models.CharField(choices=[('purchase', 'purchase'), ('production', 'production'), ('sales', 'sales'), ('adjustment', 'adjustment'), ('subcontracting_send', 'subcontracting_send'), ('subcontracting_receive', 'subcontracting_receive')], max_length=32)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('transaction_value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('source_ref', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.part')),
            ],
            options={
                'db_table': 'inventory_stock_ledger',
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('qty_per', models.DecimalField(decimal_places=6, max_digits=18)),
                ('is_direct', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.bom')),
                ('component_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_components', to='inventory.part')),
            ],
            options={
                'db_table': 'inventory_bom_items',
                'indexes': [models.Index(fields=['company_id', 'bom'], name='inventory_b_company_c8488a_idx')],
                'constraints': [models.UniqueConstraint(fields=('bom', 'component_part'), name='uq_inventory_bomitem_bom_component')],
            },
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['company_id', 'parent_part'], name='inventory_b_company_c09c43_idx'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('company_id', 'parent_part', 'revision_index'), name='uq_inventory_bom_company_parent_rev'),
        ),
        migrations.AddIndex(
            model_name='partstocksummary',
            index=models.Index(fields=['company_id', 'updated_at'], name='inventory_p_company_f5e2e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='partstocksummary',
            constraint=models.UniqueConstraint(fields=('company_id', 'part'), name='uq_inventory_stocksummary_company_part'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company_id', 'created_at'], name='inventory_s_company_e74b31_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company_id', 'part', 'created_at'], name='inventory_s_company_74d290_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company_id', 'source_type', 'created_at'], name='inventory_s_company_c2935b_idx'),
        ),
    ]
