# Generated by Django 5.2.11 on 2026-02-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledgerentry',
            name='reverse_of',
            field=models.OneToOneField(blank=True, help_text='If set, this row is the reverse/correction entry of the referenced original row.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='inventory.stockledgerentry'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company_id', 'idempotency_key'], name='inventory_s_company_8b45b1_idx'),
        ),
    ]
