# Generated by Django 5.2.10 on 2026-02-04 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=120)),
                ('scope', models.CharField(max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_events',
                'indexes': [models.Index(fields=['company_id', 'created_at'], name='audit_event_company_53e96e_idx'), models.Index(fields=['event_type', 'created_at'], name='audit_event_event_t_a71bfc_idx')],
            },
        ),
    ]
