# Generated by Django 5.2.10 on 2026-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_auditevent_audit_event_event_t_a71bfc_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditevent',
            name='audit_event_event_t_a71bfc_idx',
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_name', 'created_at'], name='audit_event_event_n_304fb7_idx'),
        ),
    ]
